spring.application.name=demo

# Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/ATM
spring.datasource.username=root
spring.datasource.password=132614
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional: Disable Whitelabel Error Page so we can handle 404s via frontend or custom handler
server.error.whitelabel.enabled=false
